import assert from "node:assert/strict"
import { readFileSync } from "node:fs"

const columnsDrawer = readFileSync("src/features/columns/ColumnsDrawer.tsx", "utf8")
const teamView = readFileSync("src/features/teams/TeamView.tsx", "utf8")
const settingsView = readFileSync("src/features/settings/SettingsView.tsx", "utf8")
const borrowLanQrCard = readFileSync("src/features/borrow/BorrowLanQrCard.tsx", "utf8")
const assetDashboardView = readFileSync("src/features/assets/AssetDashboard.tsx", "utf8")
const dbLocationBlock = settingsView.slice(
    settingsView.indexOf("DB Location"),
    settingsView.indexOf("DB Location") + 500,
)
const adminPortalBlock = settingsView.slice(
    settingsView.indexOf("Admin Portal"),
    settingsView.indexOf("Data-Backup"),
)

assert.match(columnsDrawer, /className="action-icon-button"/)
assert.match(columnsDrawer, /className="action-icon-button action-icon-button-danger"/)
assert.match(teamView, /className="action-icon-button"/)
assert.match(teamView, /PencilLine size=\{15\}/)
assert.match(teamView, /Trash2 size=\{15\}/)
assert.doesNotMatch(teamView, />\s*Rename\s*</)
assert.match(settingsView, /className="action-icon-button"/)
assert.match(settingsView, /KeyRound size=\{15\}/)
assert.match(settingsView, /Trash2 size=\{15\}/)
assert.doesNotMatch(settingsView, /UserRoundCheck size=\{15\}/)
assert.doesNotMatch(settingsView, /aria-label=\{`Use /)
assert.doesNotMatch(settingsView, /title=\{`Use /)
assert.match(adminPortalBlock, /Users size=\{20\}/)
assert.match(settingsView, /const adminPortalCard = useIdleCollapse\(60000, false\)/)
assert.match(adminPortalBlock, /settingsCardHeaderClass/)
assert.match(adminPortalBlock, /Preparing import\.\.\." : "Import"/)
assert.match(adminPortalBlock, />\s*TO:\s*</)
assert.match(settingsView, /Employee List/)
assert.match(settingsView, /Onboarding/)
assert.match(settingsView, /Offboarding/)
assert.match(settingsView, /Movement/)
assert.doesNotMatch(adminPortalBlock, /mt-4 grid gap-6 md:grid-cols-2/)
assert.doesNotMatch(settingsView, />\s*Import Excel\s*<\/div>/)
assert.doesNotMatch(
    settingsView,
    /Select one or multiple Excel files, then choose the columns before importing into app data\./,
)
assert.doesNotMatch(settingsView, /SQLite status:/)
assert.doesNotMatch(settingsView, /SQLite version:/)
assert.match(settingsView, /7 versions and delete after 400 days/)
assert.doesNotMatch(settingsView, /Auto backup every 7 days, keep 7 files, delete after 400 days/)
assert.match(settingsView, /Auto Save and Restore Back/)
assert.doesNotMatch(settingsView, /Auto-created before each import and when closing the app\. Click Restore to roll back\./)
assert.doesNotMatch(settingsView, /Manage local accounts in this app\. Column layout is saved per account profile\./)
assert.doesNotMatch(settingsView, /Point to a SharePoint \/ OneDrive synced folder to share data across the team\./)
assert.doesNotMatch(settingsView, /Borrow LAN &amp; Asset Import/)
assert.doesNotMatch(settingsView, /Save Borrow LAN Settings/)
assert.doesNotMatch(settingsView, /Refresh LAN IP/)
assert.match(borrowLanQrCard, /Save Borrow LAN Settings/)
assert.match(borrowLanQrCard, /Refresh LAN IP/)
assert.match(settingsView, /Data-Backup/)
assert.doesNotMatch(settingsView, /Admin Portal \(Local Accounts\)/)
assert.match(settingsView, /useIdleCollapse/)
assert.match(settingsView, /60000/)
assert.match(settingsView, /ChevronUp/)
assert.match(settingsView, /ChevronDown/)
assert.match(settingsView, /min-h-\[68px\]/)
assert.match(settingsView, /self-start/)
assert.match(settingsView, /bg-\[#161b22\]/)
assert.match(settingsView, /bg-\[#1c2128\]/)
assert.match(settingsView, /bg-\[#0d1117\]/)
assert.match(assetDashboardView, /bg-\[#151921\]/)
assert.match(assetDashboardView, /bg-\[#0b0f15\]/)
assert.match(assetDashboardView, /rounded-full border border-\[#00d68f\]/)
assert.doesNotMatch(assetDashboardView, /max-w-\[1120px\]/)
assert.doesNotMatch(dbLocationBlock, /amber-/)
assert.doesNotMatch(settingsView, /showLegacyDatabaseBackupCard/)
assert.doesNotMatch(settingsView, /Database & Backup .*2-column card/)

console.log("action-icon-ui tests passed")
